version: '3.9'

services:
  backend:
    image: sarvesh717/sands-of-time:v7
    container_name: sot_backend
    command: >
      sh -c "python3 manage.py makemigrations --noinput &&
             python3 manage.py migrate --noinput &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./game:/app
    ports:
      - "8000:8000"
    env_file:
      - ./game/.env