# Generated by Django 4.2.4 on 2023-10-23 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sand',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 12, 30)),
        ),
    ]
