# Generated by Django 4.2.4 on 2025-02-19 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sand",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 10, 27, 12, 5, 30)
            ),
        ),
    ]
