# Generated by Django 4.2.4 on 2025-07-28 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_user_sand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sand",
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 17, 30)),
        ),
    ]
