name: Build, Push & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build image & push to docker hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sarvesh717/sands-of-time
          tags: v2
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-container:
    needs: build-image
    runs-on: ubuntu-latest
    if: ${{ success() }} # Only deploy if the build was successful
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Changing directory to Sands-Of-Time-Deployment:"
            cd Sands-Of-Time-Deployment

            echo "Installing Docker and Docker Compose"
            # Install Docker
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh

            # Add current user to docker group to avoid sudo (optional)
            sudo usermod -aG docker $USER
            newgrp docker

            # Install Docker Compose v2 (integrated with Docker CLI)
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

            echo "Docker and Docker Compose installed:"
            docker --version
            docker compose version

            echo "Pulling latest changes from GitHub:"
            git pull origin main

            echo "Pulling latest images from Docker Hub:"
            docker compose pull
            docker image ls

            echo "Starting containers:"
            docker compose up -d
            docker ps -a

            echo "Deployment complete."
