name: Build, Push & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sarvesh717/sands-of-time:v2

      - name: Deploy to AWS EC2 using Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{ secrets.EC2_USER}}
          key: ${{ secrets.EC2_SSH_KEY}}
          script: |
            # Set your project directory – update if necessary
            PROJECT_DIR="/home/ec2-user/Sands-Of-Time"
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Directory $PROJECT_DIR not found. Exiting."
              exit 1
            fi
            cd "$PROJECT_DIR"
            
            # Ensure git is installed
            if ! command -v git &>/dev/null; then
              echo "git not found. Installing git..."
              sudo dnf install -y git
            fi

            # Ensure docker-compose is installed (the legacy binary or plugin)
            if ! docker compose version &>/dev/null; then
              if ! command -v docker-compose &>/dev/null; then
                echo "docker-compose not found. Installing docker-compose..."
                sudo dnf install -y docker-compose
              else
                echo "Using docker-compose binary."
              fi
            fi

            # Update repository
            git pull origin main

            # Pull updated images and bring up containers using docker compose
            sudo docker compose pull
            sudo docker image ls
            sudo docker compose up -d
            sudo docker ps -a