name: Build, Push & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build image & push to docker hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sarvesh717/sands-of-time
          tags: v2
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-container:
    needs: build-image
    runs-on: ubuntu-latest
    if: ${{ success() }} # Only deploy if the build was successful
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Listing folders in home directory:"
            ls -lah ~
            echo "Listing folders in current directory:"
            ls -lah
            echo "Changing directory to Sands-Of-Time-Deployment:"
            cd Sands-of-Time-Deployment
            echo "Pulling latest changes from GitHub:"
            git pull origin main
            echo "pulling latest images from docker hub:"
            sudo docker-compose pull
            sudo docker image ls
            sudo docker-compose up -d
            sudo docker ps -a
            echo "Deployment complete."