name: Build, Push & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build image & push to docker hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: sarvesh717/sands-of-time
          tags: v2
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-container:
    needs: build-image
    runs-on: ubuntu-latest
    if: ${{ success() }} # Only deploy if the build was successful
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Listing folders in home directory:"
            ls -lah ~
            echo "Listing folders in current directory:"
            ls -lah
            # Install git if not available
            if ! command -v git &>/dev/null; then
              echo "Git not found, installing git..."
              sudo dnf install -y git
            fi
            if [ -d "Sands-Of-Time-Deployment" ]; then
              echo "Directory exists, pulling latest changes..."
              cd Sands-Of-Time-Deployment
              git pull origin main
            else
              echo "Directory not found; cloning repository..."
              git clone https://github.com/Sarvesh521/Sands-Of-Time-Deployment.git
              cd Sands-Of-Time-Deployment
            fi
            # Deploy with Docker Compose
            sudo docker compose pull
            sudo docker image ls
            sudo docker compose up -d || true