name: Build, Push & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sarvesh717/sands-of-time:v2

      - name: Deploy to AWS EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Update and install Docker if necessary
            sudo dnf update -y
            sudo dnf install -y docker
            sudo systemctl start docker
            # Pull the latest Docker image
            sudo docker pull sarvesh717/sands-of-time:v2
            # Check if any container is using port 8000 and remove it forcefully
            CONTAINER=$(sudo docker ps -q --filter publish=8000)
            if [ -n "$CONTAINER" ]; then
              sudo docker rm -f "$CONTAINER"
            fi
            # Run a new container
            sudo docker run -d -p 8000:8000 sarvesh717/sands-of-time:v2
          EOF