name: Build, Push & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sarvesh717/sands-of-time:v2

  deploy-container:
        needs: build-and-deploy
        runs-on: ubuntu-latest
        if: ${{ success() }} # ! we only want to deploy if the build was successful
        steps:
        - name: executing remote ssh commands
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER}}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                cd Sands-Of-Time-Deployment
                git pull origin main
                sudo docker compose pull
                sudo docker compose up -d